#include <string>
#include <stdlib.h>
#include <string.h>
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
using namespace std;

//----------- get SS2 ----------//
//-> TPL file format
/*
//////////// Original SS2 file (generated by PSIPRED)
//////////// 2011-10-29  0:0:30
   1 E C   0.999  0.000  0.001
   2 N C   0.813  0.002  0.243
   3 I E   0.040  0.000  0.959
   4 E E   0.010  0.000  0.992
   5 V E   0.010  0.001  0.992
....
*/

//-> TGT file format
/*
//////////// Original SS3+SS8+ACC file (generated by PSIPRED + RaptorX-SS8 + RaptorX-ACC )
//////////// 2014-4-30  8:8:35
SS3:   H     E     L  | SS8:   H     G     I     E     B     T     S     L  | ACC:  Bury   Medium  Exposed
   0.000 0.000 1.000       0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000      0.000520 0.021237 0.978243      E 1
   0.000 0.254 0.745       0.000 0.000 0.000 0.379 0.004 0.000 0.000 0.617      0.012561 0.218901 0.768538      N 2
   0.004 0.926 0.072       0.000 0.000 0.000 0.946 0.002 0.000 0.008 0.045      0.481319 0.435151 0.083530      I 3
   0.001 0.980 0.018       0.000 0.000 0.000 0.992 0.000 0.000 0.000 0.008      0.068506 0.447094 0.484400      E 4
....
*/

int TGT_Get_SS2(string &infile,FILE *fp)
{
	ifstream fin;
	string buf,temp;
	//read
	fin.open(infile.c_str(), ios::in);
	if(fin.fail()!=0)
	{
		fprintf(stderr,"%s not found!\n",infile.c_str());
		exit(-1);
	}
	//skip1
	int len;
	for(;;)
	{
		if(!getline(fin,buf,'\n'))
		{
			fprintf(stderr,"%s format bad!\n",infile.c_str());
			exit(-1);
		}
		len=(int)buf.length();
		if(len<30)continue;
		temp=buf.substr(0,30);
		if(temp=="//////////// Original SS3+SS8+")break;
	}
	//skip2
	if(!getline(fin,buf,'\n'))
	{
		fprintf(stderr,"%s format bad!\n",infile.c_str());
		exit(-1);
	}
	if(!getline(fin,buf,'\n'))
	{
		fprintf(stderr,"%s format bad!\n",infile.c_str());
		exit(-1);
	}
	//init
	fprintf(fp,"# PSIPRED VFORMAT (PSIPRED V3.2)\n");
	fprintf(fp,"\n");
	//SS2
	int count=0;
	for(;;)
	{
		if(!getline(fin,buf,'\n'))
		{
			fprintf(stderr,"%s format bad!\n",infile.c_str());
			exit(-1);
		}
		len=(int)buf.length();
		if(len<10)break;
		//--- process SS2 in TGT file ---//
		{
			istringstream www(buf);
			vector <string> tmp_rec;
			for(int i=0;i<16;i++)
			{
				string temp;
				www>>temp;
				tmp_rec.push_back(temp);
			}
			double h_prob=atof(tmp_rec[0].c_str());
			double e_prob=atof(tmp_rec[1].c_str());
			double c_prob=atof(tmp_rec[2].c_str());
			int pos=atoi(tmp_rec[15].c_str());
			char ami=tmp_rec[14][0];
      char sse='C';
      if(h_prob>e_prob && h_prob>c_prob)sse='H';
      if(e_prob>h_prob && e_prob>c_prob)sse='E';
      //output
      fprintf(fp,"%4d %c %c %7.3f%7.3f%7.3f\n",pos,ami,sse,c_prob,h_prob,e_prob);
		}
		count++;
	}
	return count;
}

//------ main ------//
int main(int argc,char **argv)
{
	//---- TPL_PSP_Get ----//
	{
		if(argc<3)
		{
			fprintf(stderr,"TGT_Get_SS2 <tgt_file> <outfile>\n");
			exit(-1);
		}
		string file=argv[1];
		string outfile=argv[2];
		FILE *fp=fopen(outfile.c_str(),"wb");
		TGT_Get_SS2(file,fp);
		fclose(fp);
		exit(0);
	}
}
